# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec4d4091f19b5f02ef25d44fec243a4fd53dcb841474ef5174a7129bab730d4f5105585dddff8a56267c1935fbbc04bdce3d76888de8eb4e12854fadbfcac6a

test:
  secret_key_base: 3e5afe8b73723163faffe2fcfa0868f899d953a304195e638629ffa2f82358ab9310a8b988aaa210c8322c86967066b11b064c33f8dd4b2235e921d69141876c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
